/**
 * Highway SIMD-optimized floor divide for signed and unsigned integer types.
 *
 * Uses NumPy's CPU dispatch system (NPY_CPU_DISPATCH_CURFX) to compile
 * multiple target variants (SVE, ASIMD, NEON for ARM; X86_V4/V3/V2 for x86).
 * Within each variant, Highway's HWY_STATIC_DISPATCH handles sub-target
 * selection at runtime (e.g. SVE vs SVE2, AVX2 vs AVX-512).
 *
 * Baseline (plain name, e.g. npy_highway_floor_divide_s8_contig) acts as a
 * trampoline: it uses NPY_CPU_DISPATCH_CALL_XB to dispatch to the best
 * available target-specific variant at runtime.
 *
 * Two categories of operations:
 * 1. Contig (vector-vector): both inputs are contiguous arrays
 * 2. Scalar divisor: first input is contiguous array, second is a scalar
 *
 * Signed:   2x unrolled to hide load-to-use latency on ARM pipelines.
 * Unsigned: 4x unrolled (simpler path — no overflow/floor adjustment).
 */

#define _UMATHMODULE
#define _MULTIARRAYMODULE
#define NPY_NO_DEPRECATED_API NPY_API_VERSION

#include <limits>
#include <cstdint>

#include "numpy/ndarraytypes.h"
#include "numpy/npy_math.h"

// CPU dispatch macros: NPY_CPU_DISPATCH_CURFX, NPY_CPU_DISPATCH_CALL_XB, NPY_CPU_HAVE
#include "npy_cpu_dispatch.h"
// Per-source dispatch targets (SVE, etc.) — generated by mod_features.multi_targets()
#include "loops_arithmetic_floor_hwy.dispatch.h"

#include <hwy/highway.h>

#include "loops_arithmetic_floor_hwy.h"

HWY_BEFORE_NAMESPACE();

namespace HWY_NAMESPACE {

namespace hn = hwy::HWY_NAMESPACE;

template <typename T>
HWY_ATTR static void
simd_floor_divide(const T *HWY_RESTRICT src1, const T *HWY_RESTRICT src2,
                  T *HWY_RESTRICT dst, npy_intp len)
{
    constexpr T min_val = std::numeric_limits<T>::min();
    HWY_LANES_CONSTEXPR int vstep = static_cast<int>(hn::Lanes(hn::ScalableTag<T>()));

    const auto vneg_one = hn::Set(hn::ScalableTag<T>(), T(-1));
    const auto vzero = hn::Zero(hn::ScalableTag<T>());
    const auto vmin = hn::Set(hn::ScalableTag<T>(), min_val);
    const auto vone = hn::Set(hn::ScalableTag<T>(), T(1));

    bool warn_zero = false;
    bool warn_overflow = false;

    constexpr int unroll_factor = 2;
    const npy_intp vstep2 = vstep * unroll_factor;
    for (; len >= vstep2;
         len -= vstep2, src1 += vstep2, src2 += vstep2, dst += vstep2) {
        auto a0 = hn::LoadU(hn::ScalableTag<T>(), src1);
        auto b0 = hn::LoadU(hn::ScalableTag<T>(), src2);

        auto bzero0 = hn::Eq(b0, vzero);
        auto amin0 = hn::Eq(a0, vmin);
        auto bneg_one0 = hn::Eq(b0, vneg_one);
        auto overflow0 = hn::And(amin0, bneg_one0);

        if (!hn::AllFalse(hn::ScalableTag<T>(), bzero0)) {
            warn_zero = true;
        }
        if (!hn::AllFalse(hn::ScalableTag<T>(), overflow0)) {
            warn_overflow = true;
        }

        auto safe_b0 = hn::IfThenElse(hn::Or(bzero0, overflow0), vone, b0);
        auto quo0 = hn::Div(a0, safe_b0);

        auto rem0 = hn::Sub(a0, hn::Mul(quo0, safe_b0));
        auto a_pos0 = hn::Gt(a0, vzero);
        auto b_pos0 = hn::Gt(b0, vzero);
        auto same_sign0 = hn::Not(hn::Xor(a_pos0, b_pos0));
        auto rem_zero0 = hn::Eq(rem0, vzero);
        auto needs_adj0 = hn::And(hn::Not(same_sign0), hn::Not(rem_zero0));
        quo0 = hn::Add(quo0, hn::IfThenElse(needs_adj0, vneg_one, vzero));

        quo0 = hn::IfThenElse(bzero0, vzero, quo0);
        quo0 = hn::IfThenElse(overflow0, vmin, quo0);

        hn::StoreU(quo0, hn::ScalableTag<T>(), dst);

        auto a1 = hn::LoadU(hn::ScalableTag<T>(), src1 + vstep);
        auto b1 = hn::LoadU(hn::ScalableTag<T>(), src2 + vstep);

        auto bzero1 = hn::Eq(b1, vzero);
        auto amin1 = hn::Eq(a1, vmin);
        auto bneg_one1 = hn::Eq(b1, vneg_one);
        auto overflow1 = hn::And(amin1, bneg_one1);

        if (!hn::AllFalse(hn::ScalableTag<T>(), bzero1)) {
            warn_zero = true;
        }
        if (!hn::AllFalse(hn::ScalableTag<T>(), overflow1)) {
            warn_overflow = true;
        }

        auto safe_b1 = hn::IfThenElse(hn::Or(bzero1, overflow1), vone, b1);
        auto quo1 = hn::Div(a1, safe_b1);

        auto rem1 = hn::Sub(a1, hn::Mul(quo1, safe_b1));
        auto a_pos1 = hn::Gt(a1, vzero);
        auto b_pos1 = hn::Gt(b1, vzero);
        auto same_sign1 = hn::Not(hn::Xor(a_pos1, b_pos1));
        auto rem_zero1 = hn::Eq(rem1, vzero);
        auto needs_adj1 = hn::And(hn::Not(same_sign1), hn::Not(rem_zero1));
        quo1 = hn::Add(quo1, hn::IfThenElse(needs_adj1, vneg_one, vzero));

        quo1 = hn::IfThenElse(bzero1, vzero, quo1);
        quo1 = hn::IfThenElse(overflow1, vmin, quo1);

        hn::StoreU(quo1, hn::ScalableTag<T>(), dst + vstep);
    }

    for (; len >= vstep;
         len -= vstep, src1 += vstep, src2 += vstep, dst += vstep) {
        auto a = hn::LoadU(hn::ScalableTag<T>(), src1);
        auto b = hn::LoadU(hn::ScalableTag<T>(), src2);

        auto bzero = hn::Eq(b, vzero);
        auto amin = hn::Eq(a, vmin);
        auto bneg_one = hn::Eq(b, vneg_one);
        auto overflow = hn::And(amin, bneg_one);

        if (!hn::AllFalse(hn::ScalableTag<T>(), bzero)) {
            warn_zero = true;
        }
        if (!hn::AllFalse(hn::ScalableTag<T>(), overflow)) {
            warn_overflow = true;
        }

        auto safe_b = hn::IfThenElse(hn::Or(bzero, overflow), vone, b);
        auto quo = hn::Div(a, safe_b);

        auto rem = hn::Sub(a, hn::Mul(quo, safe_b));
        auto a_pos = hn::Gt(a, vzero);
        auto b_pos = hn::Gt(b, vzero);
        auto same_sign = hn::Not(hn::Xor(a_pos, b_pos));
        auto rem_zero = hn::Eq(rem, vzero);
        auto needs_adj = hn::And(hn::Not(same_sign), hn::Not(rem_zero));
        quo = hn::Add(quo, hn::IfThenElse(needs_adj, vneg_one, vzero));

        quo = hn::IfThenElse(bzero, vzero, quo);
        quo = hn::IfThenElse(overflow, vmin, quo);

        hn::StoreU(quo, hn::ScalableTag<T>(), dst);
    }

    if (warn_zero) {
        npy_set_floatstatus_divbyzero();
    }
    if (warn_overflow) {
        npy_set_floatstatus_overflow();
    }

    for (; len > 0; --len, ++src1, ++src2, ++dst) {
        const T a = *src1;
        const T b = *src2;
        if (NPY_UNLIKELY(b == 0)) {
            npy_set_floatstatus_divbyzero();
            *dst = 0;
        }
        else if (NPY_UNLIKELY(a == min_val && b == -1)) {
            npy_set_floatstatus_overflow();
            *dst = min_val;
        }
        else {
            T r = a / b;
            if (((a > 0) != (b > 0)) && ((r * b) != a)) {
                r--;
            }
            *dst = r;
        }
    }
}

template <typename T>
HWY_ATTR static void
simd_floor_divide_by_scalar(const T *HWY_RESTRICT src1, T scalar,
                             T *HWY_RESTRICT dst, npy_intp len)
{
    constexpr T min_val = std::numeric_limits<T>::min();
    HWY_LANES_CONSTEXPR int vstep = static_cast<int>(hn::Lanes(hn::ScalableTag<T>()));

    const auto vneg_one = hn::Set(hn::ScalableTag<T>(), T(-1));
    [[maybe_unused]] const auto vzero = hn::Zero(hn::ScalableTag<T>());
    const auto vmin = hn::Set(hn::ScalableTag<T>(), min_val);

    if (scalar == 0) {
        npy_set_floatstatus_divbyzero();
        for (npy_intp i = 0; i < len; ++i) {
            dst[i] = 0;
        }
        return;
    }

    if (scalar == 1) {
        for (; len >= vstep;
             len -= vstep, src1 += vstep, dst += vstep) {
            hn::StoreU(hn::LoadU(hn::ScalableTag<T>(), src1),
                       hn::ScalableTag<T>(), dst);
        }
        for (; len > 0; --len, ++src1, ++dst) {
            *dst = *src1;
        }
        return;
    }

    if (scalar == -1) {
        bool warn_overflow = false;

        for (; len >= vstep;
             len -= vstep, src1 += vstep, dst += vstep) {
            auto n = hn::LoadU(hn::ScalableTag<T>(), src1);
            auto is_min = hn::Eq(n, vmin);
            auto neg = hn::Neg(n);
            auto result = hn::IfThenElse(is_min, vmin, neg);
            hn::StoreU(result, hn::ScalableTag<T>(), dst);
            if (!hn::AllFalse(hn::ScalableTag<T>(), is_min)) {
                warn_overflow = true;
            }
        }

        for (; len > 0; --len, ++src1, ++dst) {
            const T n = *src1;
            if (n == min_val) {
                *dst = min_val;
                warn_overflow = true;
            } else {
                *dst = -n;
            }
        }

        if (warn_overflow) {
            npy_set_floatstatus_overflow();
        }
        return;
    }

    const auto v_scalar = hn::Set(hn::ScalableTag<T>(), scalar);
    for (; len >= vstep;
         len -= vstep, src1 += vstep, dst += vstep) {
        auto n = hn::LoadU(hn::ScalableTag<T>(), src1);
        auto quo = hn::Div(n, v_scalar);
        auto rem = hn::Sub(n, hn::Mul(quo, v_scalar));
        auto n_pos = hn::Gt(n, vzero);
        auto s_pos = hn::Gt(v_scalar, vzero);
        auto same_sign = hn::Not(hn::Xor(n_pos, s_pos));
        auto rem_zero = hn::Eq(rem, vzero);
        auto needs_adj = hn::And(hn::Not(same_sign), hn::Not(rem_zero));
        quo = hn::Add(quo, hn::IfThenElse(needs_adj, vneg_one, vzero));
        hn::StoreU(quo, hn::ScalableTag<T>(), dst);
    }

    for (; len > 0; --len, ++src1, ++dst) {
        const T n = *src1;
        T r = n / scalar;
        if (((n > 0) != (scalar > 0)) && ((r * scalar) != n)) {
            r--;
        }
        *dst = r;
    }
}

template <typename T>
HWY_ATTR static void
simd_floor_divide_unsigned(const T *HWY_RESTRICT src1,
                           const T *HWY_RESTRICT src2,
                           T *HWY_RESTRICT dst, npy_intp len)
{
    HWY_LANES_CONSTEXPR int vstep = static_cast<int>(hn::Lanes(hn::ScalableTag<T>()));
    const auto vzero = hn::Zero(hn::ScalableTag<T>());
    const auto vone = hn::Set(hn::ScalableTag<T>(), T(1));
    bool warn_zero = false;

    const npy_intp vstep4 = vstep * 4;
    for (; len >= vstep4;
         len -= vstep4, src1 += vstep4, src2 += vstep4, dst += vstep4) {
        auto a0 = hn::LoadU(hn::ScalableTag<T>(), src1);
        auto b0 = hn::LoadU(hn::ScalableTag<T>(), src2);
        auto bz0 = hn::Eq(b0, vzero);
        if (!hn::AllFalse(hn::ScalableTag<T>(), bz0)) warn_zero = true;
        auto q0 = hn::Div(a0, hn::IfThenElse(bz0, vone, b0));
        q0 = hn::IfThenElse(bz0, vzero, q0);
        hn::StoreU(q0, hn::ScalableTag<T>(), dst);

        auto a1 = hn::LoadU(hn::ScalableTag<T>(), src1 + vstep);
        auto b1 = hn::LoadU(hn::ScalableTag<T>(), src2 + vstep);
        auto bz1 = hn::Eq(b1, vzero);
        if (!hn::AllFalse(hn::ScalableTag<T>(), bz1)) warn_zero = true;
        auto q1 = hn::Div(a1, hn::IfThenElse(bz1, vone, b1));
        q1 = hn::IfThenElse(bz1, vzero, q1);
        hn::StoreU(q1, hn::ScalableTag<T>(), dst + vstep);

        auto a2 = hn::LoadU(hn::ScalableTag<T>(), src1 + vstep * 2);
        auto b2 = hn::LoadU(hn::ScalableTag<T>(), src2 + vstep * 2);
        auto bz2 = hn::Eq(b2, vzero);
        if (!hn::AllFalse(hn::ScalableTag<T>(), bz2)) warn_zero = true;
        auto q2 = hn::Div(a2, hn::IfThenElse(bz2, vone, b2));
        q2 = hn::IfThenElse(bz2, vzero, q2);
        hn::StoreU(q2, hn::ScalableTag<T>(), dst + vstep * 2);

        auto a3 = hn::LoadU(hn::ScalableTag<T>(), src1 + vstep * 3);
        auto b3 = hn::LoadU(hn::ScalableTag<T>(), src2 + vstep * 3);
        auto bz3 = hn::Eq(b3, vzero);
        if (!hn::AllFalse(hn::ScalableTag<T>(), bz3)) warn_zero = true;
        auto q3 = hn::Div(a3, hn::IfThenElse(bz3, vone, b3));
        q3 = hn::IfThenElse(bz3, vzero, q3);
        hn::StoreU(q3, hn::ScalableTag<T>(), dst + vstep * 3);
    }

    const npy_intp vstep2 = vstep * 2;
    for (; len >= vstep2;
         len -= vstep2, src1 += vstep2, src2 += vstep2, dst += vstep2) {
        auto a0 = hn::LoadU(hn::ScalableTag<T>(), src1);
        auto b0 = hn::LoadU(hn::ScalableTag<T>(), src2);
        auto bz0 = hn::Eq(b0, vzero);
        if (!hn::AllFalse(hn::ScalableTag<T>(), bz0)) warn_zero = true;
        auto q0 = hn::Div(a0, hn::IfThenElse(bz0, vone, b0));
        q0 = hn::IfThenElse(bz0, vzero, q0);
        hn::StoreU(q0, hn::ScalableTag<T>(), dst);

        auto a1 = hn::LoadU(hn::ScalableTag<T>(), src1 + vstep);
        auto b1 = hn::LoadU(hn::ScalableTag<T>(), src2 + vstep);
        auto bz1 = hn::Eq(b1, vzero);
        if (!hn::AllFalse(hn::ScalableTag<T>(), bz1)) warn_zero = true;
        auto q1 = hn::Div(a1, hn::IfThenElse(bz1, vone, b1));
        q1 = hn::IfThenElse(bz1, vzero, q1);
        hn::StoreU(q1, hn::ScalableTag<T>(), dst + vstep);
    }

    for (; len >= vstep;
         len -= vstep, src1 += vstep, src2 += vstep, dst += vstep) {
        auto a = hn::LoadU(hn::ScalableTag<T>(), src1);
        auto b = hn::LoadU(hn::ScalableTag<T>(), src2);
        auto bz = hn::Eq(b, vzero);
        if (!hn::AllFalse(hn::ScalableTag<T>(), bz)) warn_zero = true;
        auto q = hn::Div(a, hn::IfThenElse(bz, vone, b));
        q = hn::IfThenElse(bz, vzero, q);
        hn::StoreU(q, hn::ScalableTag<T>(), dst);
    }

    if (warn_zero) {
        npy_set_floatstatus_divbyzero();
    }

    for (; len > 0; --len, ++src1, ++src2, ++dst) {
        const T a = *src1;
        const T b = *src2;
        if (NPY_UNLIKELY(b == 0)) {
            npy_set_floatstatus_divbyzero();
            *dst = 0;
        }
        else {
            *dst = a / b;
        }
    }
}

template <typename T>
HWY_ATTR static void
simd_floor_divide_by_scalar_unsigned(const T *HWY_RESTRICT src1, T scalar,
                                      T *HWY_RESTRICT dst, npy_intp len)
{
    HWY_LANES_CONSTEXPR int vstep = static_cast<int>(hn::Lanes(hn::ScalableTag<T>()));
    [[maybe_unused]] const auto vzero = hn::Zero(hn::ScalableTag<T>());

    if (scalar == 0) {
        npy_set_floatstatus_divbyzero();
        for (npy_intp i = 0; i < len; ++i) {
            dst[i] = 0;
        }
        return;
    }

    const auto v_scalar = hn::Set(hn::ScalableTag<T>(), scalar);

    const npy_intp vstep4 = vstep * 4;
    for (; len >= vstep4;
         len -= vstep4, src1 += vstep4, dst += vstep4) {
        auto q0 = hn::Div(hn::LoadU(hn::ScalableTag<T>(), src1), v_scalar);
        hn::StoreU(q0, hn::ScalableTag<T>(), dst);

        auto q1 = hn::Div(hn::LoadU(hn::ScalableTag<T>(), src1 + vstep), v_scalar);
        hn::StoreU(q1, hn::ScalableTag<T>(), dst + vstep);

        auto q2 = hn::Div(hn::LoadU(hn::ScalableTag<T>(), src1 + vstep * 2), v_scalar);
        hn::StoreU(q2, hn::ScalableTag<T>(), dst + vstep * 2);

        auto q3 = hn::Div(hn::LoadU(hn::ScalableTag<T>(), src1 + vstep * 3), v_scalar);
        hn::StoreU(q3, hn::ScalableTag<T>(), dst + vstep * 3);
    }

    const npy_intp vstep2 = vstep * 2;
    for (; len >= vstep2;
         len -= vstep2, src1 += vstep2, dst += vstep2) {
        auto q0 = hn::Div(hn::LoadU(hn::ScalableTag<T>(), src1), v_scalar);
        hn::StoreU(q0, hn::ScalableTag<T>(), dst);

        auto q1 = hn::Div(hn::LoadU(hn::ScalableTag<T>(), src1 + vstep), v_scalar);
        hn::StoreU(q1, hn::ScalableTag<T>(), dst + vstep);
    }

    for (; len >= vstep;
         len -= vstep, src1 += vstep, dst += vstep) {
        auto q = hn::Div(hn::LoadU(hn::ScalableTag<T>(), src1), v_scalar);
        hn::StoreU(q, hn::ScalableTag<T>(), dst);
    }

    for (; len > 0; --len, ++src1, ++dst) {
        *dst = *src1 / scalar;
    }
}

} // namespace HWY_NAMESPACE

HWY_AFTER_NAMESPACE();

extern "C" {

#ifdef NPY_MTARGETS_CURRENT
/*
 * Target-specific compilation: NPY_CPU_DISPATCH_CURFX(func_name)
 * produces e.g. func_name_SVE. Uses HWY_STATIC_DISPATCH for Highway's
 * own sub-target selection (e.g. SVE vs SVE2).
 */

/* Signed integer contig (vector-vector) wrappers */
NPY_VISIBILITY_HIDDEN void
NPY_CPU_DISPATCH_CURFX(npy_highway_floor_divide_s16_contig)(char **args, npy_intp len)
{
    HWY_STATIC_DISPATCH(simd_floor_divide<int16_t>)(
        reinterpret_cast<const int16_t *>(args[0]),
        reinterpret_cast<const int16_t *>(args[1]),
        reinterpret_cast<int16_t *>(args[2]), len);
}

NPY_VISIBILITY_HIDDEN void
NPY_CPU_DISPATCH_CURFX(npy_highway_floor_divide_s32_contig)(char **args, npy_intp len)
{
    HWY_STATIC_DISPATCH(simd_floor_divide<int32_t>)(
        reinterpret_cast<const int32_t *>(args[0]),
        reinterpret_cast<const int32_t *>(args[1]),
        reinterpret_cast<int32_t *>(args[2]), len);
}

/* Signed integer scalar divisor wrappers */
NPY_VISIBILITY_HIDDEN void
NPY_CPU_DISPATCH_CURFX(npy_highway_floor_divide_s16_scalar_contig)(char **args, npy_intp len)
{
    HWY_STATIC_DISPATCH(simd_floor_divide_by_scalar<int16_t>)(
        reinterpret_cast<const int16_t *>(args[0]),
        *reinterpret_cast<const int16_t *>(args[1]),
        reinterpret_cast<int16_t *>(args[2]), len);
}

NPY_VISIBILITY_HIDDEN void
NPY_CPU_DISPATCH_CURFX(npy_highway_floor_divide_s32_scalar_contig)(char **args, npy_intp len)
{
    HWY_STATIC_DISPATCH(simd_floor_divide_by_scalar<int32_t>)(
        reinterpret_cast<const int32_t *>(args[0]),
        *reinterpret_cast<const int32_t *>(args[1]),
        reinterpret_cast<int32_t *>(args[2]), len);
}

NPY_VISIBILITY_HIDDEN void
NPY_CPU_DISPATCH_CURFX(npy_highway_floor_divide_s64_scalar_contig)(char **args, npy_intp len)
{
    HWY_STATIC_DISPATCH(simd_floor_divide_by_scalar<int64_t>)(
        reinterpret_cast<const int64_t *>(args[0]),
        *reinterpret_cast<const int64_t *>(args[1]),
        reinterpret_cast<int64_t *>(args[2]), len);
}

/* Unsigned integer contig (vector-vector) wrappers */
NPY_VISIBILITY_HIDDEN void
NPY_CPU_DISPATCH_CURFX(npy_highway_floor_divide_u16_contig)(char **args, npy_intp len)
{
    HWY_STATIC_DISPATCH(simd_floor_divide_unsigned<uint16_t>)(
        reinterpret_cast<const uint16_t *>(args[0]),
        reinterpret_cast<const uint16_t *>(args[1]),
        reinterpret_cast<uint16_t *>(args[2]), len);
}

NPY_VISIBILITY_HIDDEN void
NPY_CPU_DISPATCH_CURFX(npy_highway_floor_divide_u32_contig)(char **args, npy_intp len)
{
    HWY_STATIC_DISPATCH(simd_floor_divide_unsigned<uint32_t>)(
        reinterpret_cast<const uint32_t *>(args[0]),
        reinterpret_cast<const uint32_t *>(args[1]),
        reinterpret_cast<uint32_t *>(args[2]), len);
}

/* Unsigned integer scalar divisor wrappers */
NPY_VISIBILITY_HIDDEN void
NPY_CPU_DISPATCH_CURFX(npy_highway_floor_divide_u32_scalar_contig)(char **args, npy_intp len)
{
    HWY_STATIC_DISPATCH(simd_floor_divide_by_scalar_unsigned<uint32_t>)(
        reinterpret_cast<const uint32_t *>(args[0]),
        *reinterpret_cast<const uint32_t *>(args[1]),
        reinterpret_cast<uint32_t *>(args[2]), len);
}

#else
/*
 * Baseline compilation: plain func_name is the caller-facing entry point.
 * Dispatches at runtime to the best available target (e.g. func_name_SVE)
 * via NPY_CPU_DISPATCH_CALL_XB. If no target is available, falls through
 * to HWY_STATIC_DISPATCH (typically NEON on ARM64).
 */
typedef void (*floor_divide_func)(char **args, npy_intp len);
typedef void (*floor_divide_by_scalar_func)(char **args, npy_intp len);

/* Forward-declare target-specific variants so NPY_CPU_DISPATCH_CALL_XB can
 * reference them. Each expands to e.g. void func_name_SVE(char**, npy_intp);
 * when the SVE target is enabled in the dispatch config. */
NPY_CPU_DISPATCH_DECLARE_XB(void npy_highway_floor_divide_s16_contig,
                            (char **args, npy_intp len));
NPY_CPU_DISPATCH_DECLARE_XB(void npy_highway_floor_divide_s32_contig,
                            (char **args, npy_intp len));
NPY_CPU_DISPATCH_DECLARE_XB(void npy_highway_floor_divide_u16_contig,
                            (char **args, npy_intp len));
NPY_CPU_DISPATCH_DECLARE_XB(void npy_highway_floor_divide_u32_contig,
                            (char **args, npy_intp len));

NPY_CPU_DISPATCH_DECLARE_XB(void npy_highway_floor_divide_s16_scalar_contig,
                            (char **args, npy_intp len));
NPY_CPU_DISPATCH_DECLARE_XB(void npy_highway_floor_divide_s32_scalar_contig,
                            (char **args, npy_intp len));
NPY_CPU_DISPATCH_DECLARE_XB(void npy_highway_floor_divide_s64_scalar_contig,
                            (char **args, npy_intp len));
NPY_CPU_DISPATCH_DECLARE_XB(void npy_highway_floor_divide_u32_scalar_contig,
                            (char **args, npy_intp len));

/* 8-bit: baseline-only, bypasses SVE (too slow for narrow 8-bit types).
 * On ARM64, HWY_STATIC_DISPATCH in the baseline selects NEON/ASIMD. */

/* Signed 8-bit contig (vector-vector) wrapper */
NPY_VISIBILITY_HIDDEN void
NPY_CPU_DISPATCH_CURFX(npy_highway_floor_divide_s8_contig)(char **args, npy_intp len)
{
    HWY_STATIC_DISPATCH(simd_floor_divide<int8_t>)(
        reinterpret_cast<const int8_t *>(args[0]),
        reinterpret_cast<const int8_t *>(args[1]),
        reinterpret_cast<int8_t *>(args[2]), len);
}

/* Signed 8-bit scalar divisor wrapper */
NPY_VISIBILITY_HIDDEN void
NPY_CPU_DISPATCH_CURFX(npy_highway_floor_divide_s8_scalar_contig)(char **args, npy_intp len)
{
    HWY_STATIC_DISPATCH(simd_floor_divide_by_scalar<int8_t>)(
        reinterpret_cast<const int8_t *>(args[0]),
        *reinterpret_cast<const int8_t *>(args[1]),
        reinterpret_cast<int8_t *>(args[2]), len);
}

/* Unsigned 8-bit contig (vector-vector) wrapper */
NPY_VISIBILITY_HIDDEN void
NPY_CPU_DISPATCH_CURFX(npy_highway_floor_divide_u8_contig)(char **args, npy_intp len)
{
    HWY_STATIC_DISPATCH(simd_floor_divide_unsigned<uint8_t>)(
        reinterpret_cast<const uint8_t *>(args[0]),
        reinterpret_cast<const uint8_t *>(args[1]),
        reinterpret_cast<uint8_t *>(args[2]), len);
}

/* Signed integer contig (vector-vector) wrappers */
NPY_VISIBILITY_HIDDEN void
NPY_CPU_DISPATCH_CURFX(npy_highway_floor_divide_s16_contig)(char **args, npy_intp len)
{
    floor_divide_func _f = NULL;
    NPY_CPU_DISPATCH_CALL_XB(_f = npy_highway_floor_divide_s16_contig);
    if (_f != NULL) {
        _f(args, len);
        return;
    }
    HWY_STATIC_DISPATCH(simd_floor_divide<int16_t>)(
        reinterpret_cast<const int16_t *>(args[0]),
        reinterpret_cast<const int16_t *>(args[1]),
        reinterpret_cast<int16_t *>(args[2]), len);
}

NPY_VISIBILITY_HIDDEN void
NPY_CPU_DISPATCH_CURFX(npy_highway_floor_divide_s32_contig)(char **args, npy_intp len)
{
    floor_divide_func _f = NULL;
    NPY_CPU_DISPATCH_CALL_XB(_f = npy_highway_floor_divide_s32_contig);
    if (_f != NULL) {
        _f(args, len);
        return;
    }
    HWY_STATIC_DISPATCH(simd_floor_divide<int32_t>)(
        reinterpret_cast<const int32_t *>(args[0]),
        reinterpret_cast<const int32_t *>(args[1]),
        reinterpret_cast<int32_t *>(args[2]), len);
}

/* Signed integer scalar divisor wrappers */
NPY_VISIBILITY_HIDDEN void
NPY_CPU_DISPATCH_CURFX(npy_highway_floor_divide_s16_scalar_contig)(char **args, npy_intp len)
{
    floor_divide_by_scalar_func _f = NULL;
    NPY_CPU_DISPATCH_CALL_XB(_f = npy_highway_floor_divide_s16_scalar_contig);
    if (_f != NULL) {
        _f(args, len);
        return;
    }
    HWY_STATIC_DISPATCH(simd_floor_divide_by_scalar<int16_t>)(
        reinterpret_cast<const int16_t *>(args[0]),
        *reinterpret_cast<const int16_t *>(args[1]),
        reinterpret_cast<int16_t *>(args[2]), len);
}

NPY_VISIBILITY_HIDDEN void
NPY_CPU_DISPATCH_CURFX(npy_highway_floor_divide_s32_scalar_contig)(char **args, npy_intp len)
{
    floor_divide_by_scalar_func _f = NULL;
    NPY_CPU_DISPATCH_CALL_XB(_f = npy_highway_floor_divide_s32_scalar_contig);
    if (_f != NULL) {
        _f(args, len);
        return;
    }
    HWY_STATIC_DISPATCH(simd_floor_divide_by_scalar<int32_t>)(
        reinterpret_cast<const int32_t *>(args[0]),
        *reinterpret_cast<const int32_t *>(args[1]),
        reinterpret_cast<int32_t *>(args[2]), len);
}

/* int64 scalar divisor: LONG and LONGLONG both use the same i64 implementation */
NPY_VISIBILITY_HIDDEN void
NPY_CPU_DISPATCH_CURFX(npy_highway_floor_divide_s64_scalar_contig)(char **args, npy_intp len)
{
    floor_divide_by_scalar_func _f = NULL;
    NPY_CPU_DISPATCH_CALL_XB(_f = npy_highway_floor_divide_s64_scalar_contig);
    if (_f != NULL) {
        _f(args, len);
        return;
    }
    HWY_STATIC_DISPATCH(simd_floor_divide_by_scalar<int64_t>)(
        reinterpret_cast<const int64_t *>(args[0]),
        *reinterpret_cast<const int64_t *>(args[1]),
        reinterpret_cast<int64_t *>(args[2]), len);
}

/* Unsigned integer contig (vector-vector) wrappers */
NPY_VISIBILITY_HIDDEN void
NPY_CPU_DISPATCH_CURFX(npy_highway_floor_divide_u16_contig)(char **args, npy_intp len)
{
    floor_divide_func _f = NULL;
    NPY_CPU_DISPATCH_CALL_XB(_f = npy_highway_floor_divide_u16_contig);
    if (_f != NULL) {
        _f(args, len);
        return;
    }
    HWY_STATIC_DISPATCH(simd_floor_divide_unsigned<uint16_t>)(
        reinterpret_cast<const uint16_t *>(args[0]),
        reinterpret_cast<const uint16_t *>(args[1]),
        reinterpret_cast<uint16_t *>(args[2]), len);
}

NPY_VISIBILITY_HIDDEN void
NPY_CPU_DISPATCH_CURFX(npy_highway_floor_divide_u32_contig)(char **args, npy_intp len)
{
    floor_divide_func _f = NULL;
    NPY_CPU_DISPATCH_CALL_XB(_f = npy_highway_floor_divide_u32_contig);
    if (_f != NULL) {
        _f(args, len);
        return;
    }
    HWY_STATIC_DISPATCH(simd_floor_divide_unsigned<uint32_t>)(
        reinterpret_cast<const uint32_t *>(args[0]),
        reinterpret_cast<const uint32_t *>(args[1]),
        reinterpret_cast<uint32_t *>(args[2]), len);
}

/* Unsigned integer scalar divisor wrappers */
NPY_VISIBILITY_HIDDEN void
NPY_CPU_DISPATCH_CURFX(npy_highway_floor_divide_u32_scalar_contig)(char **args, npy_intp len)
{
    floor_divide_by_scalar_func _f = NULL;
    NPY_CPU_DISPATCH_CALL_XB(_f = npy_highway_floor_divide_u32_scalar_contig);
    if (_f != NULL) {
        _f(args, len);
        return;
    }
    HWY_STATIC_DISPATCH(simd_floor_divide_by_scalar_unsigned<uint32_t>)(
        reinterpret_cast<const uint32_t *>(args[0]),
        *reinterpret_cast<const uint32_t *>(args[1]),
        reinterpret_cast<uint32_t *>(args[2]), len);
}

#endif
}